"""
分配策略字段控制变量测试用例

采用控制变量法，逐个测试各分配策略字段是否生效。
基准用例：所有分配策略字段使用默认值（完全匹配，默认误差范围）。
其他用例：在基准用例基础上，只改变一个分配策略字段，其他保持不变。
"""

TEST_CASES = {
    # ========== 基准用例 ==========
    # 用例0：基准用例 - 所有分配策略字段使用默认值（完全匹配，默认误差范围）
    0: {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # ========== 测试 region_match_type（推广区域预算分配策略） ==========
    # 用例1：只改变 region_match_type 为"大小关系匹配"，其他与基准用例相同
    1: {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "大小关系匹配",  # 改变：从"完全匹配"改为"大小关系匹配"
        "region_budget_range_match": None,  # 大小关系匹配时没有误差范围
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例2：region_match_type 为"完全匹配"，但误差范围改为10%（测试误差范围影响）
    2: {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 10,  # 改变：从5改为10
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例3：region_match_type 为"完全匹配"，但勾选必须达成（测试必须达成影响）
    3: {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": True,  # 改变：从False改为True
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # ========== 测试 stage_match_type（阶段预算分配策略） ==========
    # 用例4：只改变 stage_match_type 为"大小关系匹配"，其他与基准用例相同
    4: {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "大小关系匹配",  # 改变：从"完全匹配"改为"大小关系匹配"
        "stage_range_match": None,  # 大小关系匹配时没有误差范围
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例5：stage_match_type 为"完全匹配"，但误差范围改为30%（测试误差范围影响）
    5: {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 30,  # 改变：从20改为30
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # ========== 测试 marketingfunnel_match_type（营销漏斗预算分配策略） ==========
    # 用例6：只改变 marketingfunnel_match_type 为"大小关系匹配"，其他与基准用例相同
    6: {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "大小关系匹配",  # 改变：从"完全匹配"改为"大小关系匹配"
        "marketingfunnel_range_match": None,  # 大小关系匹配时没有误差范围
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例7：marketingfunnel_match_type 为"完全匹配"，但误差范围改为25%（测试误差范围影响）
    7: {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 25,  # 改变：从15改为25
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # ========== 测试 media_match_type（媒体预算分配策略） ==========
    # 用例8：只改变 media_match_type 为"大小关系匹配"，其他与基准用例相同
    8: {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "大小关系匹配",  # 改变：从"完全匹配"改为"大小关系匹配"
        "media_range_match": None,  # 大小关系匹配时没有误差范围
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例9：media_match_type 为"完全匹配"，但误差范围改为10%（测试误差范围影响）
    9: {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 10,  # 改变：从5改为10
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # ========== 测试 mediaMarketingFunnelAdtype 相关配置 ==========
    # 用例10：allow_zero_budget 改为True（允许零预算）
    10: {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": True,  # 改变：从False改为True
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例11：mediaMarketingFunnelAdtype_target_rate 改为90%（测试目标达成率影响）
    11: {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 90,  # 改变：从80改为90
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # ========== 组合测试：多个分配策略字段同时改变 ==========
    # 用例12：region_match_type 和 stage_match_type 同时改为"大小关系匹配"
    12: {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "大小关系匹配",  # 改变
        "region_budget_range_match": None,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "大小关系匹配",  # 改变
        "stage_range_match": None,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例13：所有分配策略字段都改为"大小关系匹配"
    13: {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "大小关系匹配",  # 改变
        "region_budget_range_match": None,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "大小关系匹配",  # 改变
        "stage_range_match": None,
        "marketingfunnel_match_type": "大小关系匹配",  # 改变
        "marketingfunnel_range_match": None,
        "media_match_type": "大小关系匹配",  # 改变
        "media_range_match": None,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
}
