TEST_CASES = {
    # 用例1：全部填写，完全匹配，5%，不勾选必须达成，KPI指标第一，推广区域预算分配第二
    "完全匹配-5%-KPI第一": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement"],
        "kpi_must_achieve": True,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例2：全部填写，完全匹配，5%，不勾选必须达成，推广区域预算分配第一，KPI指标第二
    "完全匹配-5%-区域第一": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "regionBudget",
            "kpiInfo",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例2：全部填写，完全匹配，5%，不勾选必须达成，推广区域预算分配第一，KPI指标第二
    "完全匹配-5%-区域第一-允许0预算": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": True,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "regionBudget",
            "kpiInfo",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例3：全部填写，完全匹配，10%，不勾选必须达成，KPI指标第一，推广区域预算分配第二
    "完全匹配-10%-KPI第一": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement"],
        "kpi_must_achieve": True,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 10,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例4：全部填写，完全匹配，10%，不勾选必须达成，推广区域预算分配第一，KPI指标第二
    "完全匹配-10%-区域第一": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 10,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "regionBudget",
            "kpiInfo",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例7：大小关系匹配，不勾选必须达成，KPI指标第一，推广区域预算分配第二
    "大小关系匹配-不勾选必须达成-KPI第一": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement"],
        "kpi_must_achieve": True,
        "kpi_target_rate": 80,
        "region_match_type": "大小关系匹配",
        "region_budget_range_match": None,  # 大小关系匹配时没有误差范围
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例8：大小关系匹配，不勾选必须达成，推广区域预算分配第一，KPI指标第二
    "大小关系匹配-不勾选必须达成-区域第一": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "大小关系匹配",
        "region_budget_range_match": None,  # 大小关系匹配时没有误差范围
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "regionBudget",
            "kpiInfo",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例9：大小关系匹配，勾选必须达成，KPI指标第一，推广区域预算分配第二
    "大小关系匹配-勾选必须达成-KPI第一": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement"],
        "kpi_must_achieve": True,
        "kpi_target_rate": 80,
        "region_match_type": "大小关系匹配",
        "region_budget_range_match": None,  # 大小关系匹配时没有误差范围
        "region_budget_must_achieve": True,  # 勾选必须达成
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例10：大小关系匹配，勾选必须达成，推广区域预算分配第一，KPI指标第二
    "大小关系匹配-勾选必须达成-区域第一": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "大小关系匹配",
        "region_budget_range_match": None,  # 大小关系匹配时没有误差范围
        "region_budget_must_achieve": True,  # 勾选必须达成
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "regionBudget",
            "kpiInfo",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例11：全部填写，完全匹配，5%，KPI优先级：VideoViews第一，Impression第二，Engagement第三
    "完全匹配-5%-KPI第一-VideoViews优先": {
        "kpi_priority_list": ["VideoViews", "Impression", "Engagement"],
        "kpi_must_achieve": True,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例12：全部填写，完全匹配，5%，KPI优先级：Engagement第一，VideoViews第二，Impression第三
    "完全匹配-5%-KPI第一-Engagement优先": {
        "kpi_priority_list": ["Engagement", "VideoViews", "Impression"],
        "kpi_must_achieve": True,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例13：全部填写，完全匹配，5%，KPI优先级：Engagement第一，Impression第二，VideoViews第三
    "完全匹配-5%-KPI第一-Engagement优先-Impression第二": {
        "kpi_priority_list": ["Engagement", "Impression", "VideoViews"],
        "kpi_must_achieve": True,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例14：全部填写，完全匹配，5%，KPI优先级：VideoViews第一，Engagement第二，Impression第三
    "完全匹配-5%-KPI第一-VideoViews优先-Engagement第二": {
        "kpi_priority_list": ["VideoViews", "Engagement", "Impression"],
        "kpi_must_achieve": True,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例15：全部填写，完全匹配，5%，KPI优先级：Impression第一，Engagement第二，VideoViews第三
    "完全匹配-5%-KPI第一-Impression优先-Engagement第二": {
        "kpi_priority_list": ["Impression", "Engagement", "VideoViews"],
        "kpi_must_achieve": True,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
}
