TEST_CASES = {
    # 用例1：全部填写，完全匹配，5%，不勾选必须达成，KPI指标第一，推广区域预算分配第二
    "全部填写-完全匹配-5%-KPI第一-区域第二": {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例2：全部填写，完全匹配，5%，不勾选必须达成，推广区域预算分配第一，KPI指标第二
    "全部填写-完全匹配-5%-区域第一-KPI第二": {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "regionBudget",
            "kpiInfo",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例3：全部填写，完全匹配，10%，不勾选必须达成，KPI指标第一，推广区域预算分配第二
    "全部填写-完全匹配-10%-KPI第一-区域第二": {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 10,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例4：全部填写，完全匹配，10%，不勾选必须达成，推广区域预算分配第一，KPI指标第二
    "全部填写-完全匹配-10%-区域第一-KPI第二": {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 10,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "regionBudget",
            "kpiInfo",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例5：部分填写，完全匹配，5%，不勾选必须达成，KPI指标第一，推广区域预算分配第二
    "部分填写-完全匹配-5%-KPI第一-区域第二": {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例6：部分填写，完全匹配，5%，不勾选必须达成，推广区域预算分配第一，KPI指标第二
    "部分填写-完全匹配-5%-区域第一-KPI第二": {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "完全匹配",
        "region_budget_range_match": 5,
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "regionBudget",
            "kpiInfo",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例7：大小关系匹配，不勾选必须达成，KPI指标第一，推广区域预算分配第二
    "大小关系匹配-不勾选必须达成-KPI第一-区域第二": {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "大小关系匹配",
        "region_budget_range_match": None,  # 大小关系匹配时没有误差范围
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例8：大小关系匹配，不勾选必须达成，推广区域预算分配第一，KPI指标第二
    "大小关系匹配-不勾选必须达成-区域第一-KPI第二": {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "大小关系匹配",
        "region_budget_range_match": None,  # 大小关系匹配时没有误差范围
        "region_budget_must_achieve": False,
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "regionBudget",
            "kpiInfo",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例9：大小关系匹配，勾选必须达成，KPI指标第一，推广区域预算分配第二
    "大小关系匹配-勾选必须达成-KPI第一-区域第二": {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "大小关系匹配",
        "region_budget_range_match": None,  # 大小关系匹配时没有误差范围
        "region_budget_must_achieve": True,  # 勾选必须达成
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "regionBudget",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
    # 用例10：大小关系匹配，勾选必须达成，推广区域预算分配第一，KPI指标第二
    "大小关系匹配-勾选必须达成-区域第一-KPI第二": {
        "kpi_priority_list": [
            "Impression",
            "VideoViews",
            "Engagement",
            "Clicks",
            "LinkClicks",
            "Followers",
            "Like",
            "Purchase",
        ],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "region_match_type": "大小关系匹配",
        "region_budget_range_match": None,  # 大小关系匹配时没有误差范围
        "region_budget_must_achieve": True,  # 勾选必须达成
        "region_budget_target_rate": 90,
        "region_kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelAdtype_target_rate": 80,
        "mediaMarketingFunnelAdtype_must_achieve": False,
        "module_priority_list": [
            "regionBudget",
            "kpiInfo",
            "media",
            "marketingFunnel",
            "stage",
            "regionKPI",
            "mediaMarketingFunnelAdtype",
        ],
    },
}
