"""
小米版 Stage-Media 预算占比稳定性测试集

目标：
1. 重点验证不同策略下，各 stage 内 media 预算占比是否出现异常大幅波动。
2. 用控制变量法覆盖匹配方式、误差范围、模块优先级、must_achieve 与目标达成率。
"""

TEST_CASES = {
    # ========== 基准 ==========
    "稳定性-基准-完全匹配默认配置": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement", "Clicks"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelFormat_target_rate": 80,
        "mediaMarketingFunnelFormat_must_achieve": False,
        "mediaMarketingFunnelFormatBudgetConfig_target_rate": 80,
        "mediaMarketingFunnelFormatBudgetConfig_must_achieve": False,
        "module_priority_list": [
            "kpiInfo",
            "media",
            "marketingFunnel",
            "stage",
            "mediaMarketingFunnelFormat",
            "mediaMarketingFunnelFormatBudgetConfig",
        ],
    },
    # ========== Stage 策略 ==========
    "稳定性-Stage严格-误差10": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement", "Clicks"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 10,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelFormat_target_rate": 80,
        "mediaMarketingFunnelFormat_must_achieve": False,
        "mediaMarketingFunnelFormatBudgetConfig_target_rate": 80,
        "mediaMarketingFunnelFormatBudgetConfig_must_achieve": False,
        "module_priority_list": [
            "stage",
            "media",
            "kpiInfo",
            "marketingFunnel",
            "mediaMarketingFunnelFormat",
            "mediaMarketingFunnelFormatBudgetConfig",
        ],
    },
    "稳定性-Stage宽松-误差30": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement", "Clicks"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 30,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelFormat_target_rate": 80,
        "mediaMarketingFunnelFormat_must_achieve": False,
        "mediaMarketingFunnelFormatBudgetConfig_target_rate": 80,
        "mediaMarketingFunnelFormatBudgetConfig_must_achieve": False,
        "module_priority_list": [
            "stage",
            "media",
            "kpiInfo",
            "marketingFunnel",
            "mediaMarketingFunnelFormat",
            "mediaMarketingFunnelFormatBudgetConfig",
        ],
    },
    "稳定性-Stage大小关系匹配": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement", "Clicks"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "stage_match_type": "大小关系匹配",
        "stage_range_match": None,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelFormat_target_rate": 80,
        "mediaMarketingFunnelFormat_must_achieve": False,
        "mediaMarketingFunnelFormatBudgetConfig_target_rate": 80,
        "mediaMarketingFunnelFormatBudgetConfig_must_achieve": False,
        "module_priority_list": [
            "stage",
            "media",
            "kpiInfo",
            "marketingFunnel",
            "mediaMarketingFunnelFormat",
            "mediaMarketingFunnelFormatBudgetConfig",
        ],
    },
    # ========== Media 策略 ==========
    "稳定性-Media严格-误差3": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement", "Clicks"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 3,
        "allow_zero_budget": False,
        "mediaMarketingFunnelFormat_target_rate": 80,
        "mediaMarketingFunnelFormat_must_achieve": False,
        "mediaMarketingFunnelFormatBudgetConfig_target_rate": 80,
        "mediaMarketingFunnelFormatBudgetConfig_must_achieve": False,
        "module_priority_list": [
            "media",
            "stage",
            "kpiInfo",
            "marketingFunnel",
            "mediaMarketingFunnelFormat",
            "mediaMarketingFunnelFormatBudgetConfig",
        ],
    },
    "稳定性-Media宽松-误差10": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement", "Clicks"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 10,
        "allow_zero_budget": False,
        "mediaMarketingFunnelFormat_target_rate": 80,
        "mediaMarketingFunnelFormat_must_achieve": False,
        "mediaMarketingFunnelFormatBudgetConfig_target_rate": 80,
        "mediaMarketingFunnelFormatBudgetConfig_must_achieve": False,
        "module_priority_list": [
            "media",
            "stage",
            "kpiInfo",
            "marketingFunnel",
            "mediaMarketingFunnelFormat",
            "mediaMarketingFunnelFormatBudgetConfig",
        ],
    },
    "稳定性-Media大小关系匹配": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement", "Clicks"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "大小关系匹配",
        "media_range_match": None,
        "allow_zero_budget": False,
        "mediaMarketingFunnelFormat_target_rate": 80,
        "mediaMarketingFunnelFormat_must_achieve": False,
        "mediaMarketingFunnelFormatBudgetConfig_target_rate": 80,
        "mediaMarketingFunnelFormatBudgetConfig_must_achieve": False,
        "module_priority_list": [
            "media",
            "stage",
            "kpiInfo",
            "marketingFunnel",
            "mediaMarketingFunnelFormat",
            "mediaMarketingFunnelFormatBudgetConfig",
        ],
    },
    # ========== Stage + Media 组合 ==========
    "稳定性-StageMedia双大小关系匹配": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement", "Clicks"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "stage_match_type": "大小关系匹配",
        "stage_range_match": None,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "大小关系匹配",
        "media_range_match": None,
        "allow_zero_budget": False,
        "mediaMarketingFunnelFormat_target_rate": 80,
        "mediaMarketingFunnelFormat_must_achieve": False,
        "mediaMarketingFunnelFormatBudgetConfig_target_rate": 80,
        "mediaMarketingFunnelFormatBudgetConfig_must_achieve": False,
        "module_priority_list": [
            "stage",
            "media",
            "kpiInfo",
            "marketingFunnel",
            "mediaMarketingFunnelFormat",
            "mediaMarketingFunnelFormatBudgetConfig",
        ],
    },
    "稳定性-Stage严格+Media严格": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement", "Clicks"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 10,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 3,
        "allow_zero_budget": False,
        "mediaMarketingFunnelFormat_target_rate": 80,
        "mediaMarketingFunnelFormat_must_achieve": False,
        "mediaMarketingFunnelFormatBudgetConfig_target_rate": 80,
        "mediaMarketingFunnelFormatBudgetConfig_must_achieve": False,
        "module_priority_list": [
            "stage",
            "media",
            "kpiInfo",
            "marketingFunnel",
            "mediaMarketingFunnelFormat",
            "mediaMarketingFunnelFormatBudgetConfig",
        ],
    },
    "稳定性-Stage宽松+Media宽松": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement", "Clicks"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 30,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 10,
        "allow_zero_budget": False,
        "mediaMarketingFunnelFormat_target_rate": 80,
        "mediaMarketingFunnelFormat_must_achieve": False,
        "mediaMarketingFunnelFormatBudgetConfig_target_rate": 80,
        "mediaMarketingFunnelFormatBudgetConfig_must_achieve": False,
        "module_priority_list": [
            "stage",
            "media",
            "kpiInfo",
            "marketingFunnel",
            "mediaMarketingFunnelFormat",
            "mediaMarketingFunnelFormatBudgetConfig",
        ],
    },
    # ========== 优先级与预算约束 ==========
    "稳定性-模块优先级-Stage第一": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement", "Clicks"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelFormat_target_rate": 80,
        "mediaMarketingFunnelFormat_must_achieve": False,
        "mediaMarketingFunnelFormatBudgetConfig_target_rate": 80,
        "mediaMarketingFunnelFormatBudgetConfig_must_achieve": False,
        "module_priority_list": [
            "stage",
            "media",
            "kpiInfo",
            "marketingFunnel",
            "mediaMarketingFunnelFormat",
            "mediaMarketingFunnelFormatBudgetConfig",
        ],
    },
    "稳定性-模块优先级-Media第一": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement", "Clicks"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelFormat_target_rate": 80,
        "mediaMarketingFunnelFormat_must_achieve": False,
        "mediaMarketingFunnelFormatBudgetConfig_target_rate": 80,
        "mediaMarketingFunnelFormatBudgetConfig_must_achieve": False,
        "module_priority_list": [
            "media",
            "stage",
            "kpiInfo",
            "marketingFunnel",
            "mediaMarketingFunnelFormat",
            "mediaMarketingFunnelFormatBudgetConfig",
        ],
    },
    "稳定性-预算强约束-AdformatBudget必须达成90": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement", "Clicks"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 80,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": False,
        "mediaMarketingFunnelFormat_target_rate": 90,
        "mediaMarketingFunnelFormat_must_achieve": False,
        "mediaMarketingFunnelFormatBudgetConfig_target_rate": 90,
        "mediaMarketingFunnelFormatBudgetConfig_must_achieve": True,
        "module_priority_list": [
            "mediaMarketingFunnelFormatBudgetConfig",
            "stage",
            "media",
            "kpiInfo",
            "marketingFunnel",
            "mediaMarketingFunnelFormat",
        ],
    },
    "稳定性-预算弱约束-AdformatBudget70可零预算": {
        "kpi_priority_list": ["Impression", "VideoViews", "Engagement", "Clicks"],
        "kpi_must_achieve": False,
        "kpi_target_rate": 70,
        "stage_match_type": "完全匹配",
        "stage_range_match": 20,
        "marketingfunnel_match_type": "完全匹配",
        "marketingfunnel_range_match": 15,
        "media_match_type": "完全匹配",
        "media_range_match": 5,
        "allow_zero_budget": True,
        "mediaMarketingFunnelFormat_target_rate": 70,
        "mediaMarketingFunnelFormat_must_achieve": False,
        "mediaMarketingFunnelFormatBudgetConfig_target_rate": 70,
        "mediaMarketingFunnelFormatBudgetConfig_must_achieve": False,
        "module_priority_list": [
            "stage",
            "media",
            "kpiInfo",
            "marketingFunnel",
            "mediaMarketingFunnelFormat",
            "mediaMarketingFunnelFormatBudgetConfig",
        ],
    },
}
